language: java
jdk:
- openjdk8
script: mvn --fail-never -T 1C -Pdeploy clean test deploy --settings .travis-settings.xml
  -Dgpg.skip=true
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - SONATYPE_USER=mihxil
  - secure: iTQsiv5bbhEE/b8lZ8z8H9p+zSlrQck+NyEqHHmginGwuKIHnHF3HA7fmZX45C55Qa3FFcSkCX90cqsGoUP4bJu5Ky0+QmW9Du03Wy6OA61AnzeeUhD3xfqrZjBjCvtBZ+FHcBEhcp9KCPhOElM1ya9o41hXkIzmU3vpla5eCaJpz5HXt7G/+/ldWqBHNFGdpsm3O/84OG3t0FJ3SAnB70/aTTjsw3kmRRxdCRl6iS4fijHsLFIr1S3OHt3gbqHnsucXXGWA4oGptw2FSZE1QhyWIqdfT3UbO3U97bFdOxoO4Y/tGzdmk24IWup8T+4P/zAgllFqISnh9v5wqRtTBYHuCQCTJoNSi9CkD2NAd8Hrr5kYV7zPOqYgSeFu99dhG86g4Gc3W5JFg0C6ku44vPwg3Sh3lb4JsoOMwNfdzSl5sfpxOlTEN0g89T9odG85DeNc7yTYpGFeKDQTtElCmpzT1u/S73TMzEWJs3HQq20FTLLOd9QizsHG8OBWQQ/pKfxdAxOgitBV5awj4h0sLpwdAjYpmfswuD8l/44BPcTbL9xx4ZNBmlv4a5q4bniCpj8NzaEgIkRvPfQHyBIpRbOpzHBLhBCXrF9P8oqAPvs8rOE159Lj8S2ObgH7k3U0esku3NrTMWLOztnKnEcvyp/IPrjKcMvOSCy5E48ro3I=
