= MMBase Bridge Interface

image:https://github.com/mmbase/mmbase-bridge/workflows/build/badge.svg?[Build Status,link=https://github.com/mmbase/mmbase-bridge/actions?query=workflow%3Abuild]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/org.mmbase/mmbase-bridge.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/org/mmbase/mmbase-bridge]
image:https://img.shields.io/maven-central/v/org.mmbase/mmbase-bridge.svg?label=Maven%20Central[Maven Central,link=https://search.maven.org/search?q=g:%22org.mmbase%22
image:http://www.javadoc.io/badge/org.mmbase/mmbase-bridge.svg?color=blue[javadoc,link=http://www.javadoc.io/doc/org.mmbase/mmbase-bridge]
image:https://codecov.io/gh/mmbase/mmbase-bridge/branch/master/graph/badge.svg[codecov,link=https://codecov.io/gh/mmbase/mmbase-bridge]



MMBase Bridge is a part of MMBase, but can also be used in
other projects. Its main goal is to contain the 'bridge' api to talk to MMBase.
But it has a few other things too:

* 'bridge': These things can be distinguished but are are actually very related to each other.
** The Bridge API itself (org.mmbase.bridge)
** A SearchQuery abstraction and implementation (org.mmbase.storage.search)
** A DataType framework, plus a bunch if implementations (org.mmbase.datatypes).
** MMBase security API
* A Portal framework (org.mmbase.framework)
* Utils to work with this bridge (org.mmbase.bridge.util)
* A mock implementation of this bridge (org.mmbase.bridge.mock)
* A caching framework. Could perhaps be (partially) moved to utils
* A function framework (org.mmbase.util.functions). This depends on DataTypes.
